apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

images:
- name: pe
  newName: my-registry/systolic-pe
  newTag: latest
- name: orchestrator
  newName: my-registry/systolic-orchestrator
  newTag: latest

resources:
- ../../base

configMapGenerator:
- name: making-waves-environment-vars
  behavior: replace
  env: making-waves-demo.env

patches:
- path: systolic-pe-job-patch.yaml
  target:
    kind: Job
    name: systolic-pe
- path: systolic-orchestrator-service-patch.yaml
  target:
    kind: Service
    name: systolic-orchestrator